version: "1"

services:
  - type: static_site
    name: dashboard-web
    plan: starter
    rootDir: dashboard-web
    buildCommand: npm install --prefix dashboard-web && npm run build --prefix dashboard-web
    publishPath: dist
