version: "1"

services:
  - name: dashboard-web
    type: static_site
    plan: starter
    serviceDetails:
      rootDir: .
      buildCommand: ./render-build.sh
      publishPath: dashboard-web/dist
    env: {}
